version: '3.8'
networks: 
  private:
    external:
      name: private
  web:
    external: 
      name: web

 
services:
      
#---------------------
# api
#---------------------
  stage-api:
    build:
      context: .
      args:
        - PATH_OF_WAR=${PATH_OF_WAR}
    image: stage-api
    container_name: stage-api
    depends_on:
      - mysql
    environment:
      spring.datasource.username: ${MYSQL_USERNAME}
      spring.datasource.password: ${MYSQL_ROOT_PASSWORD}
      spring.profiles.active: ${ENV}
      spring.datasource.url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?serverTimezone=Europe/Berlin
      server.port: 80
    labels:
      - traefik.enable=true
      - "traefik.http.routers.stage-api.entrypoints=websecure"
      - traefik.http.routers.stage-api.rule=Host(`stage-api.dsp4-5archio19-ah-je-gh-yb.fr`)
      - traefik.http.services.stage-api.loadbalancer.server.port=80
      - "traefik.http.routers.stage-api.tls.certresolver=lets-encr"
      #prochaine ligne est peut etre inutile
      - traefik.http.routers.stage-api.middlewares=corsheaders
    networks: 
      - private
      - web
      
      
      