version: '3.8'
networks: 
  mysql_private:
    external: true 
volumes:
  mysql-data:

services:
# #---------------------
# # mysql database
# #--------------------- 
#   docker-mysql:
#     container_name: docker-mysql
#     image: mysql
#     ports:
#       - 3306:3306 #VM:Containter
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#     volumes:
#       - $PWD/sql-backup/:/backup/

# #---------------------
# # phpmyadmin
# #---------------------  
#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: docker-phpmyadmin
#     depends_on:
#       - docker-mysql
#     ports:
#       - 8081:80 #VM:Containter
#     environment:
#       MYSQL_USERNAME: ${MYSQL_USERNAME}
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       PMA_HOST: docker-mysql

#---------------------
# api
#---------------------
  api:
    build:
      context: .
    image: web-api
    container_name: docker-api
    # ports: 
    #   - 80:80
    depends_on:
      - mysql 
    environment:
      spring.datasource.username: ${MYSQL_USERNAME}
      spring.datasource.password: ${MYSQL_ROOT_PASSWORD}
      spring.profiles.active: ${ENV}
      spring.datasource.url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?serverTimezone=Europe/Berlin
      server.port: 80
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`dsp4-5archio19-ah-je-gh-yb.fr/api`)
    networks: 
      - mysql_private

      
